### ISSUE TITLE
to_dict() is not recursive when Prodict objects are nested

### ISSUE THREAD

**Issue by achaiah** [ramazanpolat/prodict#13]
Hi,

It looks like the to_dict() call is not performed recursively when Prodict objects are nested. If I have classes:

```
class A(Prodict):
  someval

class B(Prodict):
  testA: A
```

Then when I call `B.to_dict()`, it is only called on the parent but does not propagate to the children (so `testA.to_dict()` is NOT called). Could you please add the ability to call `to_dict()` recursively on the nested Prodict objects as well?

Thanks

**Comment by ramazanpolat** [comment]
Good point.

Please consider the following code:

```python
class A(Prodict):
   x: int
   s: str

class B(Prodict):
   prop1: List


b = B()
b.prop = [1, 2, A(x=1, s='s')
b.to_dict()
```
If you would like to convert all `Prodict` objects to `dict `recursively, then the `class A` in the above example also must be converted to `dict` because it is en element of a property of the `class A`. And this is not good if the language itself is dynamic. Because I have to check each and every property and also each and every value in a list to check if their type is `Prodict`, then call their own `to_dict` method, then put their value in the right key. This will have a huge performance impact.

**Comment by achaiah** [comment]
Yes, that's true, that's why I suggested that maybe it should be an optional choice, e.g.:

`def to_dict(self, is_recursive=False):`

The problem I'm running into is that just calling `to_dict()` will populate the returned dictionary with `None` values for any declared but not initialized properties. That ends up being very limiting because often you'll want to serialize/deserialize (e.g. `json.dumps(a.to_dict())`) the object and send it across the wire elsewhere. Unfortunately, that serializes all the `None` values to `null` in JSON format and if you're using something like `jsonschema` to validate the messages, it messes up the validation. The other issue is that it makes the serialized object as large as it can be because all optional properties are populated with `null` rather than just omitting them.

Anyway, I can always create a dummy child class and override `to_dict()` with my desired functionality but I figured that since `to_dict()` is implemented in Prodict, one should be able to count on it being applied recursively to all Prodict objects.

**Comment by ramazanpolat** [comment]
I understood your use case and agree with you.

I believe it will be something like this:
```python
def to_dict(self, is_recursive=False, exclude_none=False):
   ...
```

**Comment by achaiah** [comment]
Awesome, you rock!

**Comment by ramazanpolat** [comment]
@achaiah It's done.

```python
class Dad(Prodict):
    name: str
    age: int


class Son(Prodict):
    father: Dad
    age: int
    name: str

son.to_dict():
# {'name': 'Jeremy', 'father': {'name': 'Bob', 'age': None}, 'age': None}
son.to_dict(exclude_none=True):
# {'name': 'Jeremy', 'father': {'name': 'Bob', 'age': None}}
son.to_dict(exclude_none=True, is_recursive=True)
# {'name': 'Jeremy', 'father': {'name': 'Bob'}}
```
