### ISSUE TITLE
Support for 'self' key

### ISSUE THREAD

**Issue by juguerre** [ramazanpolat/prodict#15]
Hi,
I'm using prodict for loading json data. 'self' field is a common field in JSON schemas and is not supported as field with prodict:

```
TypeError: __init__() got multiple values for argument 'self'
```
This due to __init__() method using kwargs, for example:

```python
def __init__(self, **kwargs):
        super().__init__(**kwargs)
...


@classmethod
    def from_dict(cls, d: dict):
        val: cls = cls(**d)
        return val  # type: cls
```
Are you planning supporting this?

**Comment by ramazanpolat** [comment]
Hello there @juguerre  

Thank you for your contribution to have a more stable `Prodict` release.

Got your problem and fixed it.
