### ISSUE TITLE
Is there a way to make prodict accept generators?

### ISSUE THREAD

**Issue by cfeied** [ramazanpolat/prodict#18]
Prodict is exactly what dictionaries should have been right from the beginning. 

My application creates **dicts** or **defaultdicts** to hold data parsed directly from received data strings. I had assumed prodict would be able to do the same, but it appears that prodict cannot accept a generator. I tried a number of different approaches, and the best I've found is to first make a dictionary and then use `prodict.from_dict()`. 

Is there a better way? 

```
s=';O2Sat:92;HR:62;RR:0'

# this works
dd1 = dict(x.split(':') for x in s.split(';') if ':' in x)   
 
# this fails with TypeError: __init__() takes 1 positional argument but 2 were given
pd1 = Prodict(x.split(':') for x in s.split(';') if ':' in x)     

# this works but is ugly
pd2 = Prodict.from_dict(dict(x.split(':') for x in s.split(';') if ':' in x))    
```

**Comment by ramazanpolat** [comment]
Hello, @cfeied just fixed this issue.

```
s = ';O2Sat:92;HR:62;RR:0'
pd1 = Prodict(x.split(':') for x in s.split(';') if ':' in x)
print(pd1)
# {'O2Sat': '92', 'HR': '62', 'RR': '0'}
```

**Comment by cfeied** [comment]
Wow
Thank you!
