### ISSUE TITLE
Pickle and JSONPickle error

### ISSUE THREAD

**Issue by jonhandlermd** [ramazanpolat/prodict#20]
Hi -- what a great library -- thank you!  I am getting errors when I try to pickle or jsonpickle.encode an object that includes a prodict dictionary.  Below is an example using jsonpickle

This works:
#######################
from prodict import Prodict as prodict
import jsonpickle

j = {}
j['jack'] = 1
j['jill'] = 2
x = jsonpickle.encode(j)
print(x)
exit()

This generates the following error when attempting jsonpickle.encode of the prodict:
Exception has occurred: KeyError
'__getnewargs__'
#######################
from prodict import Prodict as prodict
import jsonpickle

j = prodict()
j.jack = 1
j.jill = 2
x = jsonpickle.encode(j)
print(x)
exit()

###############

Suggestions?  Thanks!

**Comment by ramazanpolat** [comment]
Hi there.

You can use `to_dict` and `from_dict` methods to make it work, just like this:

```py
from prodict import Prodict as prodict
import jsonpickle

j = prodict()
j.jack = 1
j.jill = 2

encoded = jsonpickle.encode(j.to_dict())
print(encoded)

decoded = jsonpickle.decode(encoded)
print(decoded)

d = prodict.from_dict(decoded)
print(d)
```
Is this sufficient for your use case?

**Comment by jonhandlermd** [comment]
Thanks so much!

When I am making deeply embedded dicts of dicts, and classes of classes that are using prodict as in your (excellent) examples, then unwinding all that becomes very cumbersome and challenging.  I might have a class that uses multiple subclasses of type prodict, and within each of these classes there may be variables/attributes that hold prodict dictionaries that, themselves, may hold as key values other prodict dictionaries.  Now I have an instance of such an object and I want to serialize it.  Going back to find and convert each such prodict into a dictionary would be very difficult.

Suggestions?

Thanks!

Jon

**Comment by ramazanpolat** [comment]
An example code piece would be helpful for me to comprehend your case.

Just to remind you, if it may help, you can set `is_recursive` parameter of `to_dict` method to `True` to do its job recursively like this:
```py
class Dad(Prodict):
    name: str
    age: int


class Son(Prodict):
    father: Dad
    age: int
    name: str

son.to_dict():
# {'name': 'Jeremy', 'father': {'name': 'Bob', 'age': None}, 'age': None}
son.to_dict(exclude_none=True):
# {'name': 'Jeremy', 'father': {'name': 'Bob', 'age': None}}
son.to_dict(exclude_none=True, is_recursive=True)
# {'name': 'Jeremy', 'father': {'name': 'Bob'}}

```

**Comment by jonhandlermd** [comment]
Yes, that solved the issue for my more urgent need!  Thank you!

However, going forward, it’s very likely I will want to do something like the code below.  It seems like it would require many conversions from prodict to dict throughout the code to make the jsonpickle line work.  Suggestions?

from prodict import Prodict
import jsonpickle

class Dad(Prodict):
    name: str
    age: int


class Son(Prodict):
    father: Dad
    age: int
    name: str

class family_gathering():
    def __init__(self):
        self.family = [Dad(), Son()]
        self.family[0].age = 45
        self.family[0].name = 'George'
        self.family[1].age = 16
        self.family[1].name = 'Marty'
        self.family[1].father = self.family[0]

    def go_back_in_time(self, years_back):
        self.younger_selves = [Dad(), Son()]
        self.younger_selves[0].name = 'Younger ' + self.family[0].name
        self.younger_selves[0].age = self.family[0].age - years_back
        self.younger_selves[1].name = 'Little ' + self.family[1].name
        self.younger_selves[1].age = self.family[1].age - years_back
        self.younger_selves[1].father =  self.younger_selves[0]


def main():
    my_fam = family_gathering()
    #### Go back in time 10 years
    my_fam.go_back_in_time(10)
    print(jsonpickle.encode(my_fam))
    return

#################################
if __name__ == "__main__":
    main()


Jon

**Comment by ramazanpolat** [comment]
Just patched `Prodict` to be picklable.

You can use regular python `pickle` library.

Can you please use regular `pickle` just like the example below.

```py
import pickle
import jsonpickle
from prodict import Prodict


class Dad(Prodict):
    name: str
    age: int


class Son(Prodict):
    father: Dad
    age: int
    name: str


class Gathering:
    def __init__(self):
        self.family = [Dad(), Son()]
        self.family[0].age = 45
        self.family[0].name = 'George'
        self.family[1].age = 16
        self.family[1].name = 'Marty'
        self.family[1].father = self.family[0]
        self.younger_selves = []

    def go_back_in_time(self, years_back):
        self.younger_selves = [Dad(), Son()]
        self.younger_selves[0].name = 'Younger ' + self.family[0].name
        self.younger_selves[0].age = self.family[0].age - years_back
        self.younger_selves[1].name = 'Little ' + self.family[1].name
        self.younger_selves[1].age = self.family[1].age - years_back
        self.younger_selves[1].father = self.younger_selves[0]

def regular_pickle():
    my_fam = Gathering()
    my_fam.go_back_in_time(10)

    encoded = pickle.dumps(my_fam)
    print(decoded.family)
    print(decoded.younger_selves)
    decoded: Gathering = pickle.loads(encoded)
    print(decoded)
    print(decoded.family)
    print(decoded.younger_selves)

if __name__ == "__main__":
    regular_pickle()
```

**Comment by jonhandlermd** [comment]
Wow this is great — thanks!

Jon
