### ISSUE TITLE
autocompletion doest work in latest pycharm

### ISSUE THREAD

**Issue by xsoft7** [ramazanpolat/prodict#22]
Hi,

updated to the latest pycharm 2021.1 in MacOs Big sur, python 3.9

took that example from documentation:

        p = Prodict(package='Prodict', makes='Python', rock={'even': 'more!'})
        print(p)  # {'package': 'Prodict', 'makes': 'Python', 'rock': {'even': 'more!'}}
        print(p.rock.even)  # 'more!' => **no autocomplete!**

        print(type(p.rock))  #  => **no autocomplete!**
        print(p.lang)  #  => **no autocomplete!**

is it known? any suggestions other than go back to 2020.3?

**Comment by ramazanpolat** [comment]
PyCharm can autocomplete only if there is a hint about it.

The example you provided does not present an example for auto-complete. It is merely to show the dynamic properties of Prodict.

Please check `example 1`.
