### ISSUE TITLE
to_dict(exclude_none) doesn't behave as expected

### ISSUE THREAD

**Issue by andrewmellinger** [ramazanpolat/prodict#23]
Greetings!

I am switching my project over to Prodict and I really like it so far!

I am running into one issue when I save models and having it not add extra null fields. I have a nested structure with a field of type dict, and when I round-trip a data structure nulls are added even though I have "exclude_none" set to true. I have attached a sample case. I am expecting that the second stanza (some_str=World) when exported does not have a some_dict property. Can you tell me how to get Prodict to not generate the extra nulls for empty dicts?

I am running prodict 0.8.16.

Thanks for any help!

```
import json

from prodict import Prodict
from prodict import List


class MyEntry(Prodict):
    some_str: str
    some_dict: dict


class ModelConfig(Prodict):
    my_list: List[MyEntry]


data = {
    "my_list": [
        {
            "some_str": "Hello",
            "some_dict": {
                "name": "Frodo",
            }
        },
        {
            "some_str": "World"
        }
    ]
}

model = ModelConfig.from_dict(data)
print(json.dumps(model.to_dict(exclude_none=True)))
```
 
I get: 
`{"my_list": [{"some_str": "Hello", "some_dict": {"name": "Frodo"}}, {"some_str": "World", "some_dict": null}]}`

I expect: 
`{"my_list": [{"some_str": "Hello", "some_dict": {"name": "Frodo"}}, {"some_str": "World"}]}`

**Comment by ramazanpolat** [comment]
Hi.

When using the `to_dict` method, `Prodict` only checks if the properties are `None` or not. Therefore list items are not checked for None to be excluded from to output of `to_dict`.

For this reason, I've added yet another parameter for `to_dict` which is called `exclude_none_in_lists`.
If you set it to `True`, it will check each and every List item to see if it contains a `Prodict` then `exclude_none` also applied to List elements. Be aware that this makes the `to_dict` method computationally expensive, especially if you have a lot of elements in a list.

In short, you have to use `model.to_dict(exclude_none=True, exclude_none_in_lists=True)`

***Note***: Update the `Prodict` package to get the latest commits by issuing: `pip install -U prodict`

```
class MyEntry(Prodict):
    some_str: str
    some_dict: dict


class ModelConfig(Prodict):
    my_list: List[MyEntry]


data = {
    "my_list": [
        {
            "some_str": "Hello",
            "some_dict": {
                "name": "Frodo",
            }
        },
        {
            "some_str": "World"
        }
    ]
}

model = ModelConfig.from_dict(data)
print(model.to_dict(exclude_none=True))
# {'my_list': [{'some_str': 'Hello', 'some_dict': {'name': 'Frodo'}}, {'some_str': 'World', 'some_dict': None}]}
print(model.to_dict(exclude_none=True, exclude_none_in_lists=True))
# {'my_list': [{'some_str': 'Hello', 'some_dict': {'name': 'Frodo'}}, {'some_str': 'World'}]}


```

**Comment by andrewmellinger** [comment]
Works great for me!  Thanks!!
