### ISSUE TITLE
Impelement `KeyError`

### ISSUE THREAD

**Issue by ramazanpolat** [ramazanpolat/prodict#3]
When trying to access a key which is not defined, the current behavior is to return `None`. It must conform to regular `dict` and return `KeyError`.

**Comment by larryrutledge** [comment]
Returning `None` is one of the reasons I chose this library, is there a way to toggle the behavior depending on need?

**Comment by ramazanpolat** [comment]
@larryrutledge You mean returning `None` just for undefined(not annotated) keys or any key that is not set with a value?

Right now, Prodict raises `KeyError` for both situations. But I think it makes sense to return `None` for the defined keys if they are not set.

For example:
```
class Car(Prodict):
    brand: str
    year: int

honda = Car(brand='Honda')
print(honda.year) # This raises KeyError for now although it is defined in class. 
print(honda.color) # This also raises KeyError since it is not even defined or set.
```

Can you please tell me about your usage? Do you use a class derived from Prodict(just like `Car` class above) or you just use Prodict as `dict` type, like `pro = Prodict()`. 

To point your need in the example above, do you want to use `honda.color` without `KeyError` or `honda.year`, or maybe both?

**Comment by paaksing** [comment]
Returning `KeyError` is more reasonable, but it would be nice to have a toggler, like `Car.set_exception(None)` or `Car.set_exception(KeyError)`

**Comment by achaiah** [comment]
I have to second the opinion that pre-defined keys in a class should have the option of returning None. My code broke because I was relying on that cool feature of prodict :( :(   Yes, technically you could achieve the same effect with an init() block but I loved the no-boilerplate approach that prodict had. Why change it?

In your example above I'd love if `honda.year` returned `None` while `honda.color` could throw `KeyError.`

**Comment by ramazanpolat** [comment]
@achaiah your idea was also in my mind but I forgot to implement it. Thanks to your message, it is done now.

The latest behavior: all defined attributes return `None` if not set.

```py
class Car(Prodict):
    brand: str
    year: int

honda = Car(brand='Honda')
print(honda.year) # returned None
print(honda.color) # raises KeyError since it is not defined, this is default behaviour of builtin dict type of python.
```

**Comment by ramazanpolat** [comment]
> Returning `KeyError` is more reasonable, but it would be nice to have a toggler, like `Car.set_exception(None)` or `Car.set_exception(KeyError)`, or maybe on class definition as `_exception: KeyError` then manipulate the `__getattr__` and get the type hint from `_exception` and raise that or return that

With the latest release(v0.8.11), any undefined and unset key raises `KeyError` but if they are defined, they are assigned `None`, even if never set to a value. I think this will be sufficient for most of the requirements. Since `Prodict` is designed to be dot-accessible alternative of `dict`, I don't think it will be a good idea to have a toggle to change the behavior for now. Because `dict` does not have such behavior.

**Comment by achaiah** [comment]
@ramazanpolat Awesome! That seems like a reasonable approach to me. I love Prodict because I can use it in an object oriented way or as a dict. It’s nice to be able to model my data / message objects.

**Comment by ramazanpolat** [comment]
> Returning `None` is one of the reasons I chose this library, is there a way to toggle the behavior depending on need?

@larryrutledge not it returns `None`.
