### ISSUE TITLE
Default Values broken on 0.8.8

### ISSUE THREAD

**Issue by mcflis** [ramazanpolat/prodict#7]
# Description
Hey there, the deepcopy release or rather this commit (https://github.com/ramazanpolat/prodict/commit/b3d5a5ca3a8c2e1cd2c7bc0e0c08947396a5a3ae#diff-80ef36cd17fb6c6d4ffac53fefbe0f3e) brakes default values

# Steps to reproduce
1. run following example with version 0.8.8
    ```python
    from prodict import Prodict
    
    class Example(Prodict):
        some_var: int
    
        def init(self):
            self.some_var = 10
    
    e = Example.from_dict({'some_var': 20})

    # prints {'some_var': 10}
    print(e)
    ```
1. notice `some_var` is `10`

# Expected behaviour:
` {'some_var': 20}`

# Actual behaviour:
`{'some_var': 10}`

# Workaround:
revert back to v0.8.3

# Notes
Is there any specific reason for changing the order of calls [here](https://github.com/ramazanpolat/prodict/commit/b3d5a5ca3a8c2e1cd2c7bc0e0c08947396a5a3ae#diff-80ef36cd17fb6c6d4ffac53fefbe0f3eR23)? 
`init` is now called after `set_attributes`

**Comment by ramazanpolat** [comment]
I believe I changed the order accidentally. Sorry for that.

Now the order is corrected, you can update the package by `pip intall -U prodict`.
